services:
  app:
    build: .
    deploy:
      replicas: 2

  nginx:
    image: nginx:stable-alpine3.20
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    ports:
      - 8080:80
